name: CD - Deploy to AWS

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

      - name: Get Public IP
        run: echo "IP=$(terraform -chdir=terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Get Private Key
        run: |
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          terraform -chdir=terraform output -raw private_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Wait for EC2
        run: sleep 60

      - name: SSH & Deploy Container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.IP }}
          username: ec2-user
          key: ${{ env.PRIVATE_KEY }}
          script: |
            # Wait for Docker
            until docker info >/dev/null 2>&1; do
              echo "Waiting for Docker..."
              sleep 5
            done

            docker pull ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest

            docker stop strapi || true
            docker rm strapi || true

            docker run -d \
              -p 1337:1337 \
              --name strapi \
              --restart always \
              --env NODE_ENV=production \
              ${{ secrets.DOCKER_USERNAME }}/strapi-app:latest

            docker logs strapi --tail 50
